services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'catinder:latest'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
