version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres-db'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    container_name: 'redis-cache'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  app:
    depends_on:
      - postgres
      - redis
    image: 'catinder:latest'
    env_file:
      - .env
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8080:8080"

volumes:
  postgres-data:
  redis-data:
