CREATE TABLE app_user
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_name          VARCHAR(255) NOT NULL,
    user_email         VARCHAR(255) NOT NULL ,
    user_location      VARCHAR(255) NOT NULL ,
    user_role          VARCHAR(255) NOT NULL,
    user_auth_provider VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

CREATE TABLE cat
(
    cat_id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cat_profile_picture VARCHAR(255),
    cat_breed           VARCHAR(255),
    cat_gender          VARCHAR(255),
    cat_personality     VARCHAR(255),
    cat_name            VARCHAR(255) NOT NULL,
    cat_age             INTEGER NOT NULL,
    cat_owner_user_id   BIGINT NOT NULL,

    CONSTRAINT pk_cat PRIMARY KEY (cat_id),
    CONSTRAINT fk_cat_owner FOREIGN KEY (cat_owner_user_id)
        REFERENCES app_user (user_id)
);

CREATE TABLE cat_photo
(
    cat_photo_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cat_photo_caption    VARCHAR(255),
    cat_photo_url        VARCHAR(255) NOT NULL,
    cat_photo_created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    cat_photo_cat_id     BIGINT NOT NULL,
    CONSTRAINT pk_catphoto PRIMARY KEY (cat_photo_id),
    CONSTRAINT fk_cat_photo_cat FOREIGN KEY (cat_photo_cat_id)
        REFERENCES cat (cat_id)
);

CREATE TABLE event
(
    event_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_name        VARCHAR(255) NOT NULL,
    event_description VARCHAR(255) NOT NULL,
    event_location    VARCHAR(255) NOT NULL,
    event_date_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_planner_user_id BIGINT NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (event_id),
    CONSTRAINT fk_event_planner FOREIGN KEY (event_planner_user_id)
        REFERENCES app_user (user_id)
);

CREATE TABLE event_participant
(
    event_participant_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    event_participant_user_id   BIGINT NOT NULL,
    event_participant_event_id  BIGINT NOT NULL,
    CONSTRAINT pk_eventparticipant PRIMARY KEY (event_participant_id),
    CONSTRAINT fk_eventparticipant_user FOREIGN KEY (event_participant_user_id)
        REFERENCES app_user (user_id),
    CONSTRAINT fk_eventparticipant_event FOREIGN KEY (event_participant_event_id)
        REFERENCES event (event_id)
);

CREATE TABLE post
(
    post_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_image_url  VARCHAR(255),
    post_text       VARCHAR(255) NOT NULL,
    post_created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    post_author_user_id BIGINT NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (post_id),
    CONSTRAINT fk_post_author FOREIGN KEY (post_author_user_id)
        REFERENCES app_user (user_id)
);

CREATE TABLE recommendation
(
    recommendation_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    recommendation_category            VARCHAR(255) NOT NULL,
    recommendation_product_name        VARCHAR(255) NOT NULL,
    recommendation_product_description VARCHAR(255) NOT NULL,
    recommendation_product_link        VARCHAR(255) NOT NULL,
    recommendation_cat_id              BIGINT NOT NULL,
    CONSTRAINT pk_recommendation PRIMARY KEY (recommendation_id),
    CONSTRAINT fk_recommendation_cat FOREIGN KEY (recommendation_cat_id)
        REFERENCES cat (cat_id)
);

CREATE TABLE reminder
(
    reminder_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reminder_type   VARCHAR(255) NOT NULL,
    reminder_info   VARCHAR(255) NOT NULL,
    reminder_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reminder_cat_id BIGINT NOT NULL,
    CONSTRAINT pk_reminder PRIMARY KEY (reminder_id),
    CONSTRAINT fk_reminder_cat FOREIGN KEY (reminder_cat_id)
        REFERENCES cat (cat_id)
);